export const selectClassData = [
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '1학년 영어 A분반',
  },
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '2학년 영어 B분반',
  },
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '1학년 수학 A분반',
  },
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '1학년 과학 A분반',
  },
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '3학년 영어 B분반',
  },
  {
    school_id: 0,
    class_no: 11,
    grade: 6,
    year: 2024,
    className: '1학년 영어 C분반',
  },
];

export const student = {
  students: [
    {
      uid: 1,
      name: 'ss',
      class_id: 25,
      stu_no: 25,
      gender: 25,
      age: 25,
      school_id: 25,
      pin: 25,
    },
    {
      uid: 3,
      name: 'ㅈㅅ',
      class_id: 25,
      stu_no: 11,
      gender: 1,
      age: 12,
      school_id: 1,
      pin: 214231,
    },
    {
      uid: 4,
      name: '마이콜',
      class_id: 3,
      stu_no: 25,
      gender: 0,
      age: 13,
      school_id: 1,
      pin: 11321,
    },
    {
      uid: 5,
      name: 'ㅈㅅ',
      class_id: 25,
      stu_no: 11,
      gender: 1,
      age: 12,
      school_id: 1,
      pin: 214231,
    },
    {
      uid: 6,
      name: '마이클',
      class_id: 25,
      stu_no: 25,
      gender: 1,
      age: 13,
      school_id: 1,
      pin: 11321,
    },
    {
      uid: 8,
      name: '이혁진',
      class_id: 25,
      stu_no: 11,
      gender: 1,
      age: 22,
      school_id: 1,
      pin: 1234,
    },
  ],
};
